/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package troublegame;

public class PlayerEntry extends javax.swing.JFrame {

    private String playerRed;
    private String playerGreen;
    private String playerYellow;
    private String playerBlue;
    
    /**
     * Creates new form PlayerEntry
     */
    public PlayerEntry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        enterLabel = new javax.swing.JLabel();
        redPlayerField = new javax.swing.JTextField();
        redLabel = new javax.swing.JLabel();
        greenLabel = new javax.swing.JLabel();
        yellowLabel = new javax.swing.JLabel();
        blueLabel = new javax.swing.JLabel();
        greenPlayerField = new javax.swing.JTextField();
        yellowPlayerField = new javax.swing.JTextField();
        bluePlayerField = new javax.swing.JTextField();
        PlayButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playerPanel.setMinimumSize(new java.awt.Dimension(500, 500));

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        welcomeLabel.setText("Welcome to Trouble!");

        enterLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        enterLabel.setText("Please enter who will play:");

        redPlayerField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        redPlayerField.setMinimumSize(new java.awt.Dimension(190, 30));
        redPlayerField.setPreferredSize(new java.awt.Dimension(190, 30));
        redPlayerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redPlayerFieldActionPerformed(evt);
            }
        });

        redLabel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        redLabel.setText("Red:");

        greenLabel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        greenLabel.setText("Green:");

        yellowLabel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        yellowLabel.setText("Yellow:");

        blueLabel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        blueLabel.setText("Blue:");

        greenPlayerField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        greenPlayerField.setMinimumSize(new java.awt.Dimension(190, 30));
        greenPlayerField.setPreferredSize(new java.awt.Dimension(190, 30));
        greenPlayerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenPlayerFieldActionPerformed(evt);
            }
        });

        yellowPlayerField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        yellowPlayerField.setMinimumSize(new java.awt.Dimension(190, 30));
        yellowPlayerField.setPreferredSize(new java.awt.Dimension(190, 30));
        yellowPlayerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowPlayerFieldActionPerformed(evt);
            }
        });

        bluePlayerField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bluePlayerField.setMinimumSize(new java.awt.Dimension(190, 30));
        bluePlayerField.setPreferredSize(new java.awt.Dimension(190, 30));
        bluePlayerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bluePlayerFieldActionPerformed(evt);
            }
        });

        PlayButton.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        PlayButton.setText("PLAY!");
        PlayButton.setMaximumSize(new java.awt.Dimension(150, 65));
        PlayButton.setMinimumSize(new java.awt.Dimension(150, 65));
        PlayButton.setPreferredSize(new java.awt.Dimension(150, 65));
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout playerPanelLayout = new javax.swing.GroupLayout(playerPanel);
        playerPanel.setLayout(playerPanelLayout);
        playerPanelLayout.setHorizontalGroup(
            playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerPanelLayout.createSequentialGroup()
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playerPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(welcomeLabel))
                    .addGroup(playerPanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(playerPanelLayout.createSequentialGroup()
                                    .addComponent(yellowLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yellowPlayerField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(playerPanelLayout.createSequentialGroup()
                                    .addComponent(greenLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(greenPlayerField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(playerPanelLayout.createSequentialGroup()
                                    .addComponent(enterLabel)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerPanelLayout.createSequentialGroup()
                                    .addComponent(blueLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bluePlayerField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(playerPanelLayout.createSequentialGroup()
                                .addComponent(redLabel)
                                .addGap(61, 61, 61)
                                .addComponent(redPlayerField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(playerPanelLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        playerPanelLayout.setVerticalGroup(
            playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterLabel)
                .addGap(64, 64, 64)
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redPlayerField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redLabel))
                .addGap(28, 28, 28)
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenPlayerField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greenLabel))
                .addGap(26, 26, 26)
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yellowLabel)
                    .addComponent(yellowPlayerField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueLabel)
                    .addComponent(bluePlayerField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Sets Players and opens main game panel
    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        Player player = new Player();
        GameDisplay d = new GameDisplay();
        player.setPlayers(playerRed, playerBlue, playerGreen, playerYellow);
        System.out.println(player.toString());
        d.setVisible(true);
        System.out.println("Red goes first - it is " + playerRed + "'s turn!");
        this.setVisible(false);
    }//GEN-LAST:event_PlayButtonActionPerformed

    private void redPlayerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redPlayerFieldActionPerformed
        playerRed = redPlayerField.getText();
    }//GEN-LAST:event_redPlayerFieldActionPerformed

    private void greenPlayerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenPlayerFieldActionPerformed
        playerGreen = greenPlayerField.getText();
    }//GEN-LAST:event_greenPlayerFieldActionPerformed

    private void yellowPlayerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowPlayerFieldActionPerformed
        playerYellow = yellowPlayerField.getText();
    }//GEN-LAST:event_yellowPlayerFieldActionPerformed

    private void bluePlayerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bluePlayerFieldActionPerformed
        playerBlue = bluePlayerField.getText();
    }//GEN-LAST:event_bluePlayerFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PlayButton;
    private javax.swing.JLabel blueLabel;
    private javax.swing.JTextField bluePlayerField;
    private javax.swing.JLabel enterLabel;
    private javax.swing.JLabel greenLabel;
    private javax.swing.JTextField greenPlayerField;
    private javax.swing.JPanel playerPanel;
    private javax.swing.JLabel redLabel;
    private javax.swing.JTextField redPlayerField;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel yellowLabel;
    private javax.swing.JTextField yellowPlayerField;
    // End of variables declaration//GEN-END:variables
}
